// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelProviderCapabilitiesReadParams = {
/**
 * Optional provider id from the configured `model_providers` map. Omitted reads the active
 * provider selected by config resolution.
 */
modelProvider?: string | null, };
