// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelProviderCapabilities } from "./ModelProviderCapabilities";
import type { ModelProviderEnvHttpHeader } from "./ModelProviderEnvHttpHeader";

export type ModelProviderSummary = { id: string, name: string, baseUrl: string | null, wireApi: string, isActive: boolean, requiresOpenaiAuth: boolean, supportsWebsockets: boolean, envKey: string | null, envHttpHeaders: Array<ModelProviderEnvHttpHeader>, staticHttpHeaders: Array<string>, hasStaticBearerToken: boolean, hasCommandAuth: boolean, capabilities: ModelProviderCapabilities, };
